### ISSUE TITLE
Provide a way to generate 'non colorized' colorized string

### ISSUE THREAD

**Issue by vmalloc** [timofurrer/colorful#3] opened 2017-04-18 10:22 UTC
This will make it easy to format output lines like:

```
line = 'beginning of line '
line += colorful.green('remainder of line is green')
```

Currently the example above creates an already-formatted string, which loses the ability to later on decide if to use the original text or the formatted one

**Comment by vmalloc** [comment] 2017-04-18 10:23
Actually, having colorized strings support `__iadd__` would be ideal for such cases

**Comment by timofurrer** [comment] 2017-04-20 12:35
Thanks for your request! I was on vacation that's why it took some time for me to respond :beers: 

I definitely see your use case. However, to implement it with `__iadd__` and your example above:

> ```python
>line = 'beginning of line '
>line += colorful.green('remainder of line is green')
> ```

.. won't be possible. That's because `line` is of type `str`. And what happens is the following:

1. Python calls `str.__iadd__(line, colorful.green('remainder of line is green'))` that's a *NotImplemented* operation because `str` does not know of `ColorfulString`
2. Python falls back to `str.__add__` which also is not supported for `ColorfulString`
3. Python falls back to `Colorful.__radd__` which is supported but returns `str` if the left objects is not of type `ColorfulString`

It would be possible to change the current implementation of `ColorfulString.__radd__` and always return a `ColorfulString` object, but I'm not sure if that is an intuitive-enough behavior to actually implement.

I think in the case above I'd assume that the type of `line` won't change just because I add a `ColorfulString` to it ... what do you think?

**Comment by vmalloc** [comment] 2017-04-20 19:37
@timofurrer I'm a bit split on this, so I'm not sure. In any case, a helper to quickly create a colorized string will make things much clearer in cases like this, as I would simply convert my string to a 'no-op' colorizer first

**Comment by timofurrer** [comment] 2017-04-20 20:47
I though about that, too.
See  4e82ffe for a first draft.

Until this is released you could also use `colorful.format('beginning of line')` to create an unstyled `ColorfulString`.

However, there is still the open question about when to evaluate the coloring ... At the moment once you've created the `ColorfulString` it's basically already encoded with colors and you can't disable them afterwards.

At first this was intended because the color mode is inherited:

```python
import colorful

colorful.use_true_colors()

s1 = colorful.black('black')  # uses true colors because it's created on top level

with colorful.with_8_ansi_colors() as c:
    s2 = c.black('black')  # uses 8 ANSI colors because is created via 'c' which has it's own color mode

s3 = colorful.black('black')  # uses true colors again
```

I think that's still fine but colors should be evaluated when the `ColorfulString`s are converted to `str`

**Comment by vmalloc** [comment] 2017-04-21 19:35
The draft looks good IMO. For now it's great for my use case since I use `click.echo` which strips color information after the fact, so it works for me. One can easily write a formatter that discards by avoiding formatting if one wishes...

**Comment by timofurrer** [comment] 2017-04-24 08:19
> The draft looks good IMO

Cool! I'll close this issue for now - and release today a version with `colorful.str()` support.

**Closed by timofurrer** 2017-04-24 08:19 UTC
Labels: enhancement

**Comment by vmalloc** [comment] 2017-04-24 08:28
Cool! Thanks a lot!
