### ISSUE TITLE
Can't support utf-8?

### ISSUE THREAD

**Issue by elechuanwu** [timofurrer/colorful#6] opened 2017-08-07 07:05 UTC
Using colorful can not print Chinese characters. This module supports ASCII only?

**Comment by timofurrer** [comment] 2017-08-07 07:14
Can you provide an example which reproduces your issue?

**Comment by elechuanwu** [comment] 2017-08-07 07:21
![image](https://user-images.githubusercontent.com/22742613/29016190-f4fc6a16-7b83-11e7-968d-9b76248f3a00.png)

**Comment by timofurrer** [comment] 2017-08-07 07:47
Seems to be a problem.
I'll have a look at it as soon as I have some time.

In the meantime to can explicitly convert it to unicode before printing:

```python
print(unicode(colorful.red(u'🐧🎉🐧')))
```

When using Python 3 it won't be a problem:

```python
print(colorful.red('🐧🎉🐧'))
print(colorful.red('漢字'))
```

**Comment by Agnewee** [comment] 2017-11-22 12:02
Chinese is supported now

**Comment by timofurrer** [comment] 2018-01-17 19:35
Fixed with #9

**Closed by timofurrer** 2018-01-17 19:35 UTC

**Comment by elechuanwu** [comment] 2018-01-18 06:54
Thank you.
